[package]
name = "oxidize"
version = "0.1.0"
authors = ["Victor Antoniazzi <vgsantoniazzi@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.9.8"
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
